**NOT:** Bu notebook [**Patika**][P] & [**Vitra**][E] işbirliği ile **6 Temmuz - 29 Ağustos** tarihleri arasında gerçekleşen **Veri Bilimi Bootcamp** kapsamında [**Patika.dev**][P] üzerinden takip edilen [**Python-Numpy**][PN] derslerinin notlarından oluşmaktadır. 

[E]: <https://eczacibasikariyer.com.tr/>
[P]: <https://www.patika.dev/>
[PN]:<https://app.patika.dev/egitimler/veri-bilimi-patikasi/python-numpy>

---

# Numpy Nedir? / Neden Kullanılır?

Kısaca bir giriş yapalım.

<p align= "justify"> Numpy, hızlı nümerik işlemlerin yapılabilmesini sağlayan, C tabanlı bir Python kütüphanesidir. Python'ın makine diline yakın olmamasından dolayı nümerik işlemler yüksek hızda gerçekleşememektedir. Bu nedenler makine diline daha yakın bir dil olan C ile yazılmış Numpy tercih edilmektedir. </p>

> Python kodu içerisinde kullanılabilmesi için öncelikle kütüphanenin import edilmesi gerekmektedir. Aşağıdaki kod satırı ile kütüphaneyi import edebiliriz.

In [ ]:
import numpy as np 

---
---
# Numpy Array

Nedir ve nasıl oluşturulur?

---
## Nedir?

* <p align="justify"> Numpy'ı hızlı nümerik işlemler yapabilmek için kullandığı veri tipleridir. Yapı olarak Python'da bulunan list veri tiplerine benzemektedir.</p>


* <p align="justify">Python listlerin aksine içerisinde yalnızca tek bir veri türü barındırabilmektedir. Başka bir deyişle bir numpy array içerisinde aynı anda hem int hem float veri barındıramaz.</p>

---
## Array tanımlama

> Farklı veri türleri içeren çeşitli numpy arrayler tanımlayalım:

In [ ]:
#@markdown Integer
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
#@markdown String
arr = np.array(["n", "u", "m", "p", "y"])
arr

array(['n', 'u', 'm', 'p', 'y'], dtype='<U1')

> Array içerisinde birden fazla farklı veri tipi tanımlanmaya çalışılırsa tüm elemanları içerisinde bulunan en genel veri tipi olarak ele alınır.

In [ ]:
#@markdown  Burada en genel veri tipi string olduğundan tüm elemanlar string olarak ele alınır. 
arr = np.array(["n", "u", "m", "p", "y", 1, 2, 3])
arr

array(['n', 'u', 'm', 'p', 'y', '1', '2', '3'], dtype='<U1')

In [ ]:
#@markdown Burada en genel veri tipi float olduğundan tüm elemanlar float olarak ele alınır.
arr = np.array([1, 2, 4.5, 8.2, 5])
arr

array([1. , 2. , 4.5, 8.2, 5. ])

In [ ]:
#@title Sıra sende!
#@markdown Aşağıdaki alana elemanlarını tanımla ve arrayini incele.
elements = 1, 2, 4.5, 8.2, "e" #@param {type:"raw"}
arr = np.array(elements)
arr

array(['1', '2', '4.5', '8.2', 'e'], dtype='<U32')

---
### Array'in tipini manuel olarak belirleme

Yukarıda bir array tanımladığımızda array'in tipinin içerisinde bulundurduğu veri tiplerine göre otomatik olarak şekillendirdiğini gördük. Ancak bir arrayin tipini aslında arrayi tanımlarken de belirleyebiliriz.

In [ ]:
#@markdown Yukarıda yaptığımız bir örnek üzerinden gidelim. Bu örnekte eğer herhangi bir tip tanımlaması yapmazsak verinin float olarak ele alındığını gördük. Ancak burada özellikle "int" tanımladığımız için veriler int olarak ele alınacak.
arr = np.array([1, 2, 4.5, 8.2, 5], dtype = "int32")
arr

array([1, 2, 4, 8, 5], dtype=int32)

In [ ]:
#@markdown Verinin içerisinde bulunmayan bir veri tipini de arrayin tipi olarak verebiliriz. Yine aynı örnek üzerinden gidelim, ancak bu sefer veri tipimizi "string" olarak verelim
arr = np.array([1, 2, 4.5, 8.2, 5], dtype = "str")
arr

array(['1', '2', '4.5', '8.2', '5'], dtype='<U3')

> **ANCAK** bu dönüşümler yapılırken asıl veri tipinin dönüştürülen veri tipinde bir karşılığı olmasına dikkat edilmelidir.

In [ ]:
#@markdown Karakterden oluşan stringlerin int veri tipinde karşılıkları yoktur. Bu nedenle hata alırız.
arr = np.array(["n", "u", "m", "p", "y", 1, 2, 3], dtype = "int32")
arr

ValueError: ignored

In [ ]:
#@markdown Burada her bir sayı string olarak verilmiştir bu sayıların inte dönüşümü sağlanabilir.
arr = np.array(["1", "3", "4"], dtype = "int32")
arr

array([1, 3, 4], dtype=int32)

In [ ]:
#@markdown Ancak burada string verilen sayıları inte dönüştüremeyiz.
arr = np.array(["1.5", "3.5", "4.5"], dtype = "int32")
arr

ValueError: ignored

In [ ]:
#@markdown Bir üst hücredeki dönüşümü sağlamak için önce string tipindeki floata dönüştürmeli sonrasında float verilen değeri inte dönüştürmeliyiz. 
arr = np.array(["1.5", "3.5", "4.5"], dtype = "float")
arr.astype("int")
arr

array([1.5, 3.5, 4.5])

---
---
# Farklı yöntemlerle array oluşturma

Elemanları elle tanımlamak yerine çeşitli built-in fonksiyonlar kullanacağız.

---
## Zero array (0'lardan oluşan array)

Tanımlama şekli 1:
- tek boyutlu
```python
np.zeros(eleman_sayisi)
```



In [ ]:
#@markdown 10 elemanlı sıfırdan oluşan bir array tanımlayalım.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Tanımlama şekli 2:
- 2 boyutlu
```python
np.zeros((satir_sayisi, sutun_sayisi))
```
veya 
```python
np.zeros([satir_sayisi, sutun_sayisi])
```


In [ ]:
#@markdown 3 satır 5 sütuna sahip bir zero array tanımlayalım. Tanımlama esnasında satır, sütun sayısını bir **tuple** içerisinde verdiğimize dikkat edin. 
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#@markdown Bu sefer de 1 satır 3 sütuna sahip bir zero array tanımlayalım. Tanımlama esnasında satır, sütun sayısını bir **liste** içerisinde verdiğimize dikkat edin.
np.zeros([1, 3])

array([[0., 0., 0.]])

Tanımlama şekli 3:
- çok boyutlu

In [ ]:
#@markdown 3 boyutlu bir array tanımlayalım.
np.zeros([4, 3, 2]) 

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

> 0'lardan oluşan bir array tanımlarken de array tipini belirleyebiliriz.

In [ ]:
#@markdown Boolean veri tipinde sıfır değeri False değerine eşittir.
np.zeros((4, 2), dtype= "bool")

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [ ]:
#@markdown String veri tipinde sıfır değeri boş stringlere eşit olacaktır.
np.zeros((4, 2), dtype= "str")

array([['', ''],
       ['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

---
## Belirli bir elemandan array oluşturma

Tanımlama şekli:
```python
np.full(array_boyutu, eleman)
```

In [ ]:
#@markdown 3 satır 2 sütuna sahip ve 158 integer değerinden oluşan bir array tanımlayalım.
np.full((3,2), 158)

array([[158, 158],
       [158, 158],
       [158, 158]])

In [ ]:
#@markdown 3 adet "abc" stringinden oluşan bir array tanımlayalım.
np.full(3, "abc")

array(['abc', 'abc', 'abc'], dtype='<U3')

> Bu şekilde array oluştururken de veri tipini belirleyebiliriz.

In [ ]:
#@markdown 3 adet 92 değerinden oluşan ancak veri tipi string olan bir array tanımlayalım.
np.full(3, 92, dtype="str")

array(['9', '9', '9'], dtype='<U1')

---
## Ardışık sayılardan array oluşturma

> Çalışma şekli Python'da bulunan `range()` fonksiyonuna benzemektedir. Başlangıç olarak verilen sayıyı dahil, bitiş olarak verilen sayısı hariç olarak ele alır. 

Tanımlama şekli:
```python
np.arange(baslangic(dahil), bitis(hariç), adim_sayisi)
```

In [ ]:
#@markdown 1'den 10'a kadar sayılardan oluşan br array tanımlayalım. Ancak burada 10 değerinin array elemanlarına dahil edilmediğine dikkat edelim.
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#@markdown 4'er atlayan bir sayı dizisi deneyelim
np.arange(0, 16, 4) 

array([ 0,  4,  8, 12])

In [ ]:
# Geriye doğru 5'er atlayan bir sayı dizisi deneyelim.
np.arange(25, 5, -5)

array([25, 20, 15, 10])

---
## Array tanımlarken belirlenen bir aralığı eşit uzaklıktaki parçalara bölmek

> Belirlediğimiz aralığı eşit parçalara bölerek belirlediğimiz sayı kadar elemandan oluşan bir array üretir.

> **!!** `arrange()` fonksiyonunun aksine hem başlangıç hem bitiş noktalarını aralığa dahil etmektedir. 

**Örnek verelim**

---



Sınırlarımızı 1 ve 15.5 olarak belirlediğimizi varsayalım. Üretilecek eleman sayısını da 30 olarak tanımlamış olalım. Oluşacak olan array 1 ve 15.5 aralığında 30 adet sayı üretirken, ürettiği her bir sayının birbirine olan uzaklığını eşit olarak ayarlamaktadır. Yani aslında bize üreteceği sayılar şu şekilde olacaktır:
`1, 1.5, 2, 2.5, 3, ... , 15.5` 

Tanımlama şekli:
```python
np.linspace(baslangic(dahil), bitis(hariç), adim_sayisi)
```

In [ ]:
#@markdown Burada 30 adet sayı üretmesini isterken num = 30 şeklinde de tanımlayabilirdik.
np.linspace(1, 15.5, 30)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5])

In [ ]:
#@markdown Eğer biz sayı belirtmezsek default olarak eleman sayısını 50 olarak alacaktır.
np.linspace(1, 5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
#@title Sıra sende!
start = 1.5           #@param {type:"number"}
end = 10.2 #@param {type:"number"}
element_count =  4#@param {type:"integer"}
np.linspace(start, end, element_count)

array([ 1.5,  4.4,  7.3, 10.2])

---
## Normal dağılımdan array oluşturmak

> Normal dağılıma oturan elemanlardan oluşan bir array elde etmek için ```np.random.normal()``` fonksiyonundan yararlanırız. 

>Tanımlarken normal dağılımın sahip olduğu ortalama ve standart sapmanın yanı sıra oluşturulacak arrayin boyutuna da ihtiyaç duyarız.



Tanımlama şekli:
```python
np.random.normal(ortalama, standart_sapma, array_boyutu)
```

In [ ]:
#@markdown 0 ortalamaya ve 100 standart sapmasına sahip bir normal dağılımdan 3 satır 5 sütundan oluşan bir array tanımlayalım.
np.random.normal(0, 100, (3, 5))

array([[  80.54475082,  -85.41753337,   -0.92122394, -132.69090884,
        -168.35671005],
       [   4.75749916,   79.83650355,  187.99978819,  -37.76231048,
        -131.92248825],
       [  -8.9030199 ,  -63.18753799,   17.39530401,  112.13623782,
          56.43479369]])

In [ ]:
#@title Sıra sende!
mean = 0 #@param {type:"number"}
std = 15 #@param {type:"number"}
shape = 3, 2, 3 #@param {type:"raw"}

np.random.normal(mean, std, shape)

array([[[  2.46182792,  -6.85764323,  -6.91579512],
        [ -0.06791014, -19.57891126, -31.63589115]],

       [[  7.07506671, -15.53382129, -35.14602266],
        [-20.39010652,  -1.22807305,   5.50491254]],

       [[ 12.21548396,   2.74259405,  -5.04058828],
        [-22.87794343,   9.05537964,   6.30713984]]])

---
## Random integer değerlerden oluşan array oluşturmak

> Tamamen random üretilmiş integer değerlerden oluşan bir array yaratmak için ```np.random.randint()``` fonksiyonundan yararlanırız.

> `arrange()` fonksiyonu gibi başlangıç değerini aralığa dahil ederken bitiş değerini dahil etmez. 

Tanımlama şekli:
```python
np.random.randint(baslangic, bitis, array_boyutu)
```


In [ ]:
#@markdown 2'den 10'a kadar aralıktan random bir şekilde seçilmiş sayılardan oluşan 6 satır 3 sütundan oluşan bir array tanımlayalım.
np.random.randint(2, 10, (6, 3))

array([[2, 4, 2],
       [3, 5, 7],
       [3, 9, 7],
       [4, 9, 8],
       [9, 5, 7],
       [9, 7, 2]])

> **Not:** Daha öncesinde olduğu gibi shape vermeden de bu fonksiyonu kullanabiliriz. Ancak bu sefer bize yalnızca 1 değer döndürecektir.

In [ ]:
#@markdown Bu satur bize 2 ile 10 arasında seçtiği random bir sayıyı döndürecektir.
np.random.randint(2, 10)

9

In [ ]:
#@title Sıra sende!
#@markdown Aynı değerleri kullanarak hücreyi birden fazla kez çalıştır ve arrayin nasıl değiştiğini gözlemle.

start = 0 #@param {type:"integer"}
end = 15 #@param {type:"integer"}
shape = 3, 2, 3 #@param {type:"raw"}

np.random.randint(start, end, shape)



array([[[ 0,  7,  5],
        [10,  4,  7]],

       [[ 0,  0,  1],
        [ 2,  1,  2]],

       [[14,  1,  0],
        [ 5,  7,  8]]])

---
## Birim matris (identity matrix) arrayi oluşturma

Birim matris ana köşegeni birlerden ve diğer elemanları sıfırlardan oluşan n × n boyutlu bir kare matristir.

$A_{n,n} =
 \begin{pmatrix}
  1 & 0 & \cdots & 0 \\
  0 & 1 & \cdots & 0 \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  0 & 0 & \cdots & 1
 \end{pmatrix}$

Tanımlama şekli:
```python
np.eye(array_satiri, array_sutunu)
```


In [ ]:
#@markdown 5x5'lik bir birim matris arrayi oluşturalım.
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#@markdown Birim matrisin tanımı gereği tanımlanan array içerisinde kare alınabilecek en büyük matris ele alınır ve birim matris şeklinde oluşturulur. Kalan elemanların tamamı 0 olarak tanımlanır.
np.eye(4, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#@title Sıra sende!
row = 3 #@param {type:"integer"}
column = 3 #@param {type:"integer"}
np.eye(row, column)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---
---

# Arrayler ile basit matematiksel işlemler
Toplama / Çıkartma / Çarpma / Bölme

<p align= "justify"> Numpy'da array işlemleri eleman bazlı olarak gerçekleştirilmektedir. Yani işlemler arraylerin ilk elemanları arasında, arraylerin ikinci elemanları arasında, ... şeklinde olacak şekilde gerçekleştirilir. Başka bir ifadeyle arraylerin karşılıklı elemanları arasında işlemler gerçekleştirilir. Bu nedenle işlem yapılacak arraylerin boyutu birbirine eşit olmalıdır. </p>

> Birkaç örnek işlem gerçekleştirmek için bir array tanımlayalım:

In [ ]:
arr1 = np.array([1, 3, 5, 7])
arr2 = np.array([12, 34, 8, 0])

In [ ]:
#@title Toplama işlemi
#@markdown Gördüğümüz gibi karşılıklı elemanlar arasında işlemler gerçekleştiriliyor.
arr1 + arr2

array([13, 37, 13,  7])

In [ ]:
#@title Çarpma işlemi
arr1 * arr2

array([ 12, 102,  40,   0])

In [ ]:
#@title Arrayi integer ile çarpma
arr1 * 5

array([ 5, 15, 25, 35])

---
---
# Array Özelliklerini İnceleme

<p align="jutify">Kimi zamanlarda oluşturulan arraylerin boyut, eleman sayısı gibi özelliklerine ihtiyaç duyabiliriz. Bu özellikler için ise çeşitli fonksiyonlar kullanırız.</p>


![](https://aprendeconalf.es/docencia/python/manual/img/arrays.png)

> Öncelikle özelliklerini inceleyebileceğimiz birkaç array tanımlayalım:

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.zeros((3, 5, 4))

print("1. array:\n", arr1, "\n")
print("-"*30)
print("\n2. array:\n", arr2)

1. array:
 [1 2 3] 

------------------------------

2. array:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


---
## .shape
Array satır-sütun sayılarını inceleme

In [ ]:
print("1. arrayin satır sütun sayıları: ", arr1.shape)
print("2. arrayin satır sütun sayıları: ", arr2.shape)

1. arrayin satır sütun sayıları:  (3,)
2. arrayin satır sütun sayıları:  (3, 5, 4)


---
## .ndim
Array boyut sayısını inceleme (kaç boyuta sahip olduğu - dimension)

In [ ]:
print("1. arrayin boyut sayısı: ", arr1.ndim)
print("2. arrayin boyut sayısı: ", arr2.ndim)

1. arrayin boyut sayısı:  1
2. arrayin boyut sayısı:  3


---
## .size
Array eleman sayılarını inceleme

In [ ]:
print("1. arrayin eleman sayısı: ", arr1.size)
print("2. arrayin eleman sayısı: ", arr2.size)

1. arrayin eleman sayısı:  3
2. arrayin eleman sayısı:  60


---
##.dtype
Array veri tipini inceleme

In [ ]:
print("1. arrayin veri tipi: ", arr1.dtype)
print("2. arrayin veri tipi: ", arr2.dtype)

1. arrayin veri tipi:  int64
2. arrayin veri tipi:  float64


---
---
# Arrayi Yeniden Boyutlandırma 

<p align="justify">Bir arrayi farklı boyutlara dönüştürebiliriz. Ancak bunu yaparken array içerisindeki elemanları kullanacağımız için array boyutunu değiştirmeden önceki eleman sayısıyla değiştirdikten sonraki ihtiyaç duyulan eleman sayısının eşit olmasına dikkat etmeliyiz.</p>

> Örnek olarak yine bir array tanımlayalım ve sonrasında tanımladığımız bu arrayi farklı boyutlara çevirmeye çalışalım.

In [ ]:
#@markdown Yeniden boyutlandırabilmek için arrayin kaç elemandan oluştuğuna da bakalım. Arrayi yeniden boyutlandırırken bu eleman sayısını sağladığından emin olmalıyız.
arr = np.zeros((3, 6))
print("Arrayimiz:\n\n", arr,"\n", "-"*40)
print("\nArrayimizin eleman sayısı: ", arr.size)

Arrayimiz:

 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 
 ----------------------------------------

Arrayimizin eleman sayısı:  18


> Şimdi arrayimizi farklı bir boyutla ifade etmeye çalışalım. Bunun için `.reshape()` metodunu kullanacağız

In [ ]:
#@markdown Ancak bu işlemin başta tanımladığımız orijinal arrayi değiştirmediğini de unutmayalım. Arrayi tekrar yazdırdığımızda aslında boyutunun değişmediğini göreceğiz.
print("Yeniden boyutlandırılmış array:\n\n", arr.reshape(9, 2))
print("\n", "-"*20)
print("Orijinal arrayimiz:\n\n", arr)

Yeniden boyutlandırılmış array:

 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

 --------------------
Orijinal arrayimiz:

 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


> 

In [ ]:
#@markdown `.reshape()` kullanırken boyutunu değiştirmek istediğimiz ancak eleman sayısını bilmediğimiz bir array için bilmediğimiz boyutuna -1 verebiliriz. Böylece numpy, tanımlanan boyut haricinde ihtiyaç duyulan boyutu arrayin eleman sayısından kendi hesaplayacaktır.
arr.reshape(-1, 2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

---
## Array'e yeni bir boyut eklemek

> Öncelikle tanımladığımız arrayin boyutlarını tekrar bir görelim:

In [ ]:
arr.shape

(3, 6)

> Şimdiyse yeni bir boyut ekleyelim:

In [ ]:
new_arr = arr[np.newaxis, :]
print("Yeni arrayimiz:\n\n", new_arr)
print("\n", "-"*30)
print("\nYeni arrayimizin boyutları:\n\n", new_arr.shape)


Yeni arrayimiz:

 [[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]

 ------------------------------

Yeni arrayimizin boyutları:

 (1, 3, 6)


> Biraz daha farklı bir şey deneyelim:

In [ ]:
new_arr = arr[:, np.newaxis]
print("Yeni arrayimiz:\n\n", new_arr)
print("\n", "-"*30)
print("\nYeni arrayimizin boyutları:\n\n", new_arr.shape)

Yeni arrayimiz:

 [[[0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]]]

 ------------------------------

Yeni arrayimizin boyutları:

 (3, 1, 6)


> Gördüğümüz gibi arraye iki farklı şekilde boyut eklemiş olduk.

> ``np.newaxis`` yerine ``None`` yazarak da aynı sonucu elde edebilirdik

In [ ]:
new_arr = arr[:, None]
print("Yeni arrayimiz:\n\n", new_arr)
print("\n", "-"*30)
print("\nYeni arrayimizin boyutları:\n\n", new_arr.shape)

Yeni arrayimiz:

 [[[0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]]]

 ------------------------------

Yeni arrayimizin boyutları:

 (3, 1, 6)


---
---
# Arrayleri Birleştirmek

---
## Concat işlemi


> Arraylerin birleştirilme işleminde `np.concatenate()` metodu kullanılır. Bu fonksiyon kullanıldığında birleştirilen arrayler, arrayler içerisinde bulunan veri tiplerinden en genel olanını ana veri tipi olarak kabul eder ve birleştirdiği tüm elemanlara o şekilde davranır.

> <p align="justify">Concatenate işlemi yapılırken concat edilecek arraylerin aynı boyutlara sahip olmasına dikkat edilmelidir.</p>

In [ ]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[218, 12],
                 [61, 24]])

print("1. array:\n", arr1)
print("\n", "-"*20)
print("\n2. array:\n", arr2)
print("\n", "-"*20)
print("\nConcatenate işlemi:\n",np.concatenate([arr1, arr2]))


1. array:
 [[1 2]
 [3 4]]

 --------------------

2. array:
 [[218  12]
 [ 61  24]]

 --------------------

Concatenate işlemi:
 [[  1   2]
 [  3   4]
 [218  12]
 [ 61  24]]


> Concat işleminin hangi eksende gerçekleşeceğini işlemi gerçekleştirirken belirtebiliriz. Belirtilmediği sürece concat işlemi default olarak axis 0'da gerçekleştirilir.

![](https://www.w3resource.com/w3r_images/numpy-manipulation-concatenate-function-image-1.png)
![](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-58.png)


In [ ]:
#@markdown Arrayler alt alta eklendi.
np.concatenate([arr1, arr2], axis = 0)

array([[  1,   2],
       [  3,   4],
       [218,  12],
       [ 61,  24]])

In [ ]:
#@markdown Arrayler yan yana eklendi.
np.concatenate([arr1, arr2], axis = 1)

array([[  1,   2, 218,  12],
       [  3,   4,  61,  24]])

> <p align="justify">np.concatenate() fonksiyonunu kullanmak için yalnızca numpy array kullanmamız gerekmez. Python liste veya tuple veri tipleri kullanılarak da concatenate işlemi gerçekleştirilebilir.</p>


In [ ]:
arr = np.array([4, 5, 6, 7, 8])
l = [1, 2, 5]

print("Array:\n", arr)
print("\n", "-"*20)
print("\nListe:\n", l)
print( "\n", "-"*20)
print("\nArray ve liste concatenate işlemi:\n",np.concatenate([arr, l]))
print( "\n", "-"*20)
print("\nYalnızca liste concatenate işlemi:\n",np.concatenate([l, l]))

Array:
 [4 5 6 7 8]

 --------------------

Liste:
 [1, 2, 5]

 --------------------

Array ve liste concatenate işlemi:
 [4 5 6 7 8 1 2 5]

 --------------------

Yalnızca liste concatenate işlemi:
 [1 2 5 1 2 5]


---
## Stack işlemi

Concat işlemi ile arrayleri birleştirebiliyoruz ancak satır-sütun mantığına sahip olmayan arrayler için istediğimiz bir sütunda birleşme sağlayabilmek için `stack()` fonksiyonuna ihtiyaç duyarız.



<p align="justify">Stack fonksiyonu yeni bir dimension oluşturarak oluşturulan dimensionda arraylerin birleştirilmesini sağlar. Bu işlem, birleştirilmek istenen arraylere yeni bir dimension eklenip sonrasında concat edilerek de gerçekleştirilebilir.</p> 

> Öncelikle arraylerimizi tanımlayalım ve boyutlarını inceleyelim.

In [ ]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([2, 4, 6, 8, 10])

print("1. arrayimiz:\n\n", arr1)
print("\n", "-"*40)
print("\nArrayimizin boyutu: ", arr1.shape)
print("\n", "*"*40)
print("\n2. arrayimiz:\n\n", arr2)
print("\n", "-"*40)
print("\nArrayimizin boyutu: ", arr2.shape)

1. arrayimiz:

 [1 3 5 7 9]

 ----------------------------------------

Arrayimizin boyutu:  (5,)

 ****************************************

2. arrayimiz:

 [ 2  4  6  8 10]

 ----------------------------------------

Arrayimizin boyutu:  (5,)


> Her iki arrayimiz için de yalnızca 5 elemandan oluştuğuna dair bilgimiz var ancak satır sütun yapısında değiller. Stack işlemimizi gerçekleştirelim:

In [ ]:
#@markdown Birleştirdiğimiz array boyutu artık satır-sütun şeklinde.
stacked = np.stack([arr1, arr2])

print("Stack işlemi:\n\n", stacked)
print("\n", "-"*40)
print("\nYeni arrayimizin boyutu: ", stacked.shape)

Stack işlemi:

 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]

 ----------------------------------------

Yeni arrayimizin boyutu:  (2, 5)


> Bir de boyut vererek birleştirmeyi deneyelim.

In [ ]:
#@markdown Default olarak axis = 0'da stack edilir.
stacked = np.stack([arr1, arr2], axis=0)
stacked

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [ ]:
stacked = np.stack([arr1, arr2], axis=1)
stacked

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

---
---
# Arrayi Parçalara Ayırmak (Splitting) 

Kullanım şekli:

```python
np.split(bolunecek_veri, bolunecek_indexler)
```

![](https://www.w3resource.com/w3r_images/numpy-manipulation-split-function-image.png)

**NOT:** Bu fonksiyon yalnızca numpy arraylerine özgü değildir. Python listlerde de işlev görmektedir.

Bölünecek indexlerden kasıt aslında hangi indexten önceki kısmın ayrılacağıdır. Sözel bir örnek yapalım:

listemiz = [15, 16, 17, 18]

Eğer bu listeyi şu ifade ile bölersek:

* np.split(listemiz, [1,2])

Listemiz şu şekilde bölünecekti:
* 15 | 16 | 17 18 --> [15] , [16] , [17 , 18]

Gördüğümüz gibi bir nevi verdiğimiz indexlerden hemen önce listemizi kesiyoruz.

Aynı örneği bir de kod üzerinde deneyelim:

In [ ]:
l = [15, 16, 17, 18]

print("Listemiz:\n\n", l)
print("\n", "-"*40)
print("\nBölünmüş listemiz:\n\n", np.split(l, [1, 2]))

Listemiz:

 [15, 16, 17, 18]

 ----------------------------------------

Bölünmüş listemiz:

 [array([15]), array([16]), array([17, 18])]


> Aynı örneği bir de numpy array kullanarak yapalım:


In [ ]:
arr = np.array([15, 16, 17, 18])

print("Arrayimiz:\n\n", arr)
print("\n", "-"*40)
print("\nBölünmüş arrayimiz:\n\n", np.split(arr, [1, 2]))

Arrayimiz:

 [15 16 17 18]

 ----------------------------------------

Bölünmüş arrayimiz:

 [array([15]), array([16]), array([17, 18])]


> np.split() fonksiyonunun sonucu olan her eleman her zaman array olarak döner!

* ANCAK np.split() fonksiyonundan birden fazla array döndüğü için bu arrayler tek bir liste içerisinde tutulur.

* YANİ örneğin bir listeyi böldüğümüzde çıktıda 3 adet array oluşuyorsa kullanılan np.split() fonksiyonu 3 adet arrayden oluşan bir listeye eşittir.

Birden fazla dimensiona (boyuta) sahip arrayleri split etmek için split edeceğimiz ekseni bilmemiz gerekir. Bu durumlarda vsplit ve hsplitten yararlanırız.

> Öncelikle bu fonksiyonları görebilmek için bir array üretelim:

In [ ]:
arr = np.arange(30).reshape(3,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

---
## vsplit (vertical split)
Satırlara göre bölme

In [ ]:
#@markdown Bu durumda index = 1 olan sütundan hemen önce arrayimizi bölmüş oluruz. 
np.vsplit(arr, [1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [ ]:
#@markdown Bu durumda arrayimizi üç parçaya böldük.
np.vsplit(arr, [1, 2])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

---
## hsplit (horizontical split)
Sütunlara göre bölme

In [ ]:
#@markdown Bu durumda index = 2 olan sütundan hemen önce (üçüncü sütun) arrayimizi bölmüş oluruz. 
np.hsplit(arr, [2])

[array([[ 0,  1],
        [10, 11],
        [20, 21]]), array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19],
        [22, 23, 24, 25, 26, 27, 28, 29]])]

In [ ]:
#@markdown Bu durumda arrayimizi yine üç parçaya böldük.
np.hsplit(arr, [3, 6])

[array([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]]), array([[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]), array([[ 6,  7,  8,  9],
        [16, 17, 18, 19],
        [26, 27, 28, 29]])]

---
---
# Arraylerde sıralama (sorting)

Kullanım şekli:

```python
np.sort(array)
```

> **Not:** `.sort()` küçükten büyüğe sıralama yapar.

In [ ]:
arr = [15, 35, 1, 49, 26, 42, 3, 49]
arr

print("Sıralamadan önce arrayimiz:\n\n", arr)
print("\n", "-"*40)
print("\nSıralanmış arrayimiz:\n\n", np.sort(arr))
print("\n", "-"*40)
print("\nSıralandıktan sonra orijinal arrayimiz:\n\n", arr)

Sıralamadan önce arrayimiz:

 [15, 35, 1, 49, 26, 42, 3, 49]

 ----------------------------------------

Sıralanmış arrayimiz:

 [ 1  3 15 26 35 42 49 49]

 ----------------------------------------

Sıralandıktan sonra orijinal arrayimiz:

 [15, 35, 1, 49, 26, 42, 3, 49]


> Not: `.sort()` metodu `np.sort(array)` şeklinde kullanıldığında orijinal array üzerinde değişiklik yapmaz. Array üzerinde güncelleme yapılabilmesi için `array.sort()` şeklinde kullanılmalıdır.

In [ ]:
#@markdown Orijinal arrayimiz üzerinde sıralama yapalım 
arr.sort()
print("\nSıralandıktan sonra orijinal arrayimiz:\n\n", arr)


Sıralandıktan sonra orijinal arrayimiz:

 [1, 3, 15, 26, 35, 42, 49, 49]


---
## argsort()


> küçükten büyüğe sıralar ancak çıktıda sıralanmış değerlerin önceki indexlerini döndürür.


In [ ]:
arr = [15, 35, 1, 49, 26, 42, 3, 49]

In [ ]:
np.argsort(arr)

array([2, 6, 0, 4, 1, 5, 3, 7])

---
---
# Arraylerde Indexleme
Çok boyutlu arraylerde elemanlara erişme

---
## Temel Indexleme

> Öncelikle elemanlarına erişebilmek için bir array tanımlayalım:


In [ ]:
arr = np.arange(40).reshape(4, 10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

Arraylerde bir elemanın indexini verirken aynı `.reshape`'de verdiğimiz gibi önce satır sonra sütun veririz.

In [ ]:
#@markdown Bu bize arrayin son satırını döndürecektir.
arr[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [ ]:
#@markdown Bu ise bize arrayin son satırının ilk elemanını döndürecektir. Bunu arr[3, 0] şeklinde de verebilirdik.
arr[3][0]

30

In [ ]:
#@markdown Bir arrayin belli bir indexindeki değerini bu şekilde değiştirebiliriz.
arr[3, 0] = 0
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
#@markdown Arrayin bir indexindeki değeri arrayin sahip olduğu veri tipi dışında bir veri tipine dönüştürmek arrayin veri tipini değiştirmez. Tüm değerler arrayin veri tipine cast olur.
arr[0, 0] = 100.15
arr

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [  0,  31,  32,  33,  34,  35,  36,  37,  38,  39]])

In [ ]:
#@markdown Ancak cast dönüşümü iki basamaklıysa bu dönüşüm yapılamaz.
arr[0, 0] = "100.15"
arr

ValueError: ignored

---
## Bölerek Indexleme (Slice Indexing)

Bu özellik python liste benzemektedir. Bu nedenle yalnızca birkaç örnek yapacağız.

In [ ]:
#@markdown Bu bize index 0'dan 3'e olan satırları getirecektir.
arr[0:3]

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [ ]:
#@markdown Bu bize yalnızca index=2den başlayarak kalan satırları getirecektir.
arr[2:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 0, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
#@markdown Bu ise index 1'den başlayarak 2 2 ilerler ve kalan tüm satırları getirir.
arr[1::2]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
#@markdown index 1'deki sütunun tüm satırlarını döndürür.
arr[:, 1]

array([ 1, 11, 21, 31])

In [ ]:
#@markdown index 1'deki sütunun 2 2 atlayarak kalan satırlarını döndürür.
arr[::2, 1]

array([ 1, 21])

In [ ]:
#@markdown Bu sefer hem sütun hem satırda bölerek aldık.
arr[:2, 2:3]

array([[ 2],
       [12]])

---
## Spesifik Indexlerdeki Değerleri Döndürme (Fancy Indexing)

Bunu gerçekleştirmek için erişmek istediğimiz indexleri içeren bir liste oluştururuz. Sonrasında aynı indexlemede yaptığımıza benzer bir şekilde köşeli parantezler yardımıyla indexleri içeren listeyi kullanırız. 

In [ ]:
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#@markdown Burada değerler bizim indexlerini verdiğimiz sırada döner.
index_list = [5, 7, 9, 2, 1]
arr[index_list]

array([10, 14, 18,  4,  2])

In [ ]:
#@markdown Çok boyutlu arraylerde de bu özelliği kullanabiliriz.
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#@markdown Burada satır bazında index = 2'ye sahip olan satırı alırken sütun bazında fancy indexing yaparken birden fazla elemanın indexini aldık.
arr[2, [1, 2, 4]]

array([11, 12, 14])

In [ ]:
#@markdown Burada satır bazında tüm satırları ele alırken sütun bazında fancy indexing yapmış olduk.
arr[:, [1, 2, 4]]

array([[ 1,  2,  4],
       [ 6,  7,  9],
       [11, 12, 14],
       [16, 17, 19]])

In [ ]:
#@markdown Burada ise hem sütun hem satır bazlı bi indexing yaptık.
arr[[0, 2, 3],[0, 3, 4]]

array([ 0, 13, 19])

> ANCAK hem sütun hem satır bazlı fancy indexing yapılırken verilen listeler eşit uzunluğa sahip olmalı. Çünkü verilen satır indexleri ile sütun indexleri birebir karşılaştırılır ve kesişen elemanlar döndürülür.

> Örnekten gidecek olursak arrayimizin:
* 0. satırında ve 0. sütununda bulunan elemanını
* 2. satırında ve 3. sütununda bulunan elemanını
* 3. satırında ve 4. sütununda bulunan elamanını
elde etmiş olduk.

In [ ]:
#@markdown Ayrıca fancy indexingi döndürdüğümüz indexlerdeki değerleri değiştirmek için de kullanabiliriz.
arr[[0, 2, 3],[0, 3, 4]] = [100, 120, 130]
arr

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12, 120,  14],
       [ 15,  16,  17,  18, 130]])

---
## Indexing Yaparken Koşul Verme (Conditional Indexing)


In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#@markdown Eğer direkt olarak arrayi bir koşulda kullanırsak arrayin her bir elemanı koşulda sınanır ve array uzunluğunda bool (True/False) değerlerden oluşan bir array çıktısı alırız.
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
#@markdown Ancak koşulu indexing yapar gibi köşeli parantezler yardımıyla verirsek bu durumda koşulu sağlayan elemanlar bir array olarak dönecektir.
arr[arr > 5]

array([6, 7, 8, 9])

> Koşulu yalnızca tek bir arrayin elemanları üzerinden vermek zorunda değiliz. İki array arasında da koşullardan yararlanabiliriz.

In [ ]:
arr2 = np.arange(0, 20, 2)
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#@markdown İki array arasında indexler karşılıklı olarak karşılaştırıldı ve bize aynı indexte aynı eleman bulunuyorsa yalnızca o eleman döndü.
arr[arr == arr2]

array([0])

In [ ]:
#@markdown Birden fazla koşul ve/veya ile bağlanacaksa bu durumda bu koşulların short circuit halleriyle yani `|` ve `&` operatörleriyle koşullar verilmelidir. 
arr[(arr >= 2) & (arr <= 6)]

array([2, 3, 4, 5, 6])

In [ ]:
#@markdown Yazılan koşulun değilinin alınması için tilda (`~`) işaretinden yararlanılır.
arr[~((arr >= 2) & (arr <= 6))]

array([0, 1, 7, 8, 9])

> Birden fazla boyutlu arraylerde koşul verilirken dönen değerler çok boyutlu bir array şeklinde değil yalnızca tek boyutlu bir array (sayı öbeği) şeklinde döner. 

In [ ]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

---
---
# Subarray Mantığı
Arrayimizin alt arrayi

Arraylerde de python liste benzer bir hafızaya kaydetme mantığı vardır. Bu nedenle bir arrayin subarrayi üzerinde işlem yapmak aslında ana array üzerinde de işlem yapmak anlamına gelmektedir.

In [ ]:
arr = np.arange(40).reshape(4, 10)
subarr = arr[1:, 2:5]


print("Ana arrayimiz:\n\n", arr)
print("\n", "-"*40)
print("\nSubarrayimiz:\n\n", subarr)

Ana arrayimiz:

 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]

 ----------------------------------------

Subarrayimiz:

 [[12 13 14]
 [22 23 24]
 [32 33 34]]


In [ ]:
#@markdown Subarrayimiz üzerinde işlem yapalım ve subarray ile ana array üzerinde değişiklik olmuş mu inceleyelim.
subarr[2,0] = 100


print("Değişiklikten sonra subarrayimiz:\n\n", subarr)
print("\n", "-"*40)
print("\nDeğişiklikten sonra ana arrayimiz:\n\n", arr)


Değişiklikten sonra subarrayimiz:

 [[ 12  13  14]
 [ 22  23  24]
 [100  33  34]]

 ----------------------------------------

Değişiklikten sonra ana arrayimiz:

 [[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31 100  33  34  35  36  37  38  39]]


> Eğer ana array üzerinde işlem yapılmak istenmiyorsa, değişikliğin yalnızca subarray üzerine etkimesi isteniyorsa `.copy()` metodunden yararlanılmalıdır. Bu sayede artık iki array hafızada aynı yeri işaret etmez, subarrayimiz hafızada ayrı bir yere shaip olur.

In [ ]:
arr = np.arange(40).reshape(4, 10) # Ana arrayimiz
copyarr = arr[1:, 2:5].copy() # Kopya arrayimiz

copyarr[2,0] = 100 # Kopya arrayimiz üzerinde işlemimiz

print("Ana arrayimiz:\n\n", arr)
print("\n", "-"*40)
print("Kopya arrayimiz:\n\n", copyarr)
print("\n", "-"*40)
print("Değişiklikten sonra kopya arrayimiz:\n\n", copyarr)
print("\n", "-"*40)
print("\nDeğişiklikten sonra ana arrayimiz:\n\n", arr)

Ana arrayimiz:

 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]

 ----------------------------------------
Kopya arrayimiz:

 [[ 12  13  14]
 [ 22  23  24]
 [100  33  34]]

 ----------------------------------------
Değişiklikten sonra kopya arrayimiz:

 [[ 12  13  14]
 [ 22  23  24]
 [100  33  34]]

 ----------------------------------------

Değişiklikten sonra ana arrayimiz:

 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


---
---
# Array Elemanları ile Toplu İşlemler

---
## sum() Metodu

Bir arrayin elemanlarını toplamak için kullanılır.

Kullanım şekli:
```python
np.sum(array)
```

In [ ]:
arr = np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
#@markdown Arrayin tüm elemanlarını toplamış olduk.
np.sum(arr)

190

In [ ]:
#@markdown Koşul vererek arrayin yalnızca 10'dan büyük elemanlarını toplamış olduk.
np.sum(arr[(arr > 10)])

135

Axis bazlı .sum () metodunu nasıl kullandığımıza bir bakalım.

![](https://www.programmersought.com/images/204/357bdcc35c9cbd123dce1855aec99184.gif)

In [ ]:
#@markdown Array elemanlarını arrayi tek satıra indirgeyecekmiş gibi toplar. Yani ilk eleman için ele aldığımızda; (0 + 4 + 8 + 12 + 16) = 40
np.sum(arr, axis = 0)

array([40, 45, 50, 55])

In [ ]:
#@markdown Array elemanlarını arrayi tek sütuna indirgeyecekmiş gibi toplar. Yani ilk eleman için ele aldığımızda; (0 + 1 + 2 + 3) = 6
np.sum(arr, axis = 1)

array([ 6, 22, 38, 54, 70])

> Bu metodu farklı amaçlarla da kullanabiliriz. Örneğin bir koşulumuz var ve bu koşulun arrayin kaç elemanı tarafından sağlandığını öğrenmek istiyoruz. Arrayi direkt koşul içerisinde kullandığımızda array uzunluğunda bool değerlerden oluşan bir array elde ettiğimizi hatırlayalım. Buradaki True değerler aynı zamanda 1'e de karşılık geleceği için sum() metoduyla amacımıza ulaşabiliriz. 

In [ ]:
#@markdown Arrayimizin kaç elemanının 10'dan büyük olduğuna bakalım.
np.sum(arr > 10)

9

---
## all() Metodu

Bir arrayin bütün elemanlarının verilen koşula uyup uymadığının kontrolünü yapar.


Kullanım şekli:
```python
np.all(kosul)
```

In [ ]:
arr = np.arange(0, 20, 2).reshape(2,5)
arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
#@markdown Öncelikle koşulumuzun Bool çıktısına bir bakalım.
arr > 5

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
#@markdown Arrayin içerisinde 9'dan küçük elemanlar da olduğu için False döndürdü.
np.all(arr > 5)

False

In [ ]:
#@markdown Öncelikle koşulumuzun Bool çıktısına bir bakalım.
arr % 2 == 0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
#@markdown Arrayin tüm elemanları çift sayı olduğundan True döndürdü.
np.all(arr % 2 == 0)

True

> Bu metodu da sum()'da olduğu gibi axis bazlı bakabiliriz.

In [ ]:
#@markdown Axis=0 doğrultusunda bakacaktır bu nedenle 5 adet Bool değer döndürür. index = 4 ve sonraki sütunlarda bu koşul sağlandığı için yalnızca son iki değer True dönecektir.
np.all(arr > 5, axis = 0)

array([False, False, False,  True,  True])

In [ ]:
#@markdown Axis=1 doğrultusunda bakacaktır bu nedenle 2 adet Bool değer döndürür. İlk satırın tüm elemanları koşulu sağlamadığı için False, ikinci satırın tüm elemanları koşulu sağladığı için True döndürür.
np.all(arr > 5, axis = 1)

array([False,  True])

## any() Metodu

Arrayin herhangi bir elemanının verilen koşulu sağlayıp sağlamadığının kontrolünü yapar. np.all() metoduna çok benzer bir yapıya sahiptir.

Kullanım şekli:
```python
np.any(kosul)
```

In [ ]:
arr = np.arange(0, 20, 2).reshape(2,5)
arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
#@markdown Öncelikle koşulumuzun Bool çıktısına bir bakalım.
arr > 16

array([[False, False, False, False, False],
       [False, False, False, False,  True]])

In [ ]:
#@markdown Arrayin en az 1 elemanı koşulu sağladığı için True döner.
np.any(arr > 16)

True

> Bu metodu da axis bazlı kullanabiliriz.

In [ ]:
#@markdown Axis=0 doğrultusunda bakacaktır bu nedenle 5 adet Bool değer döndürür. Yalnızca son sütunda en az 1 eleman koşulu sağladığı için son eleman True, kalanı False döner.
np.any(arr > 16, axis = 0)

array([False, False, False, False,  True])

In [ ]:
#@markdown Axis=1 doğrultusunda bakacaktır bu nedenle 2 adet Bool değer döndürür. İlk satırın herhangi bir elemanı koşulu sağlamadığı için False, ikinci satırın en az 1 elemanı koşulu sağladığı için True döner.
np.any(arr > 16, axis = 1)

array([False,  True])

---
---
# Numpy Cheatsheet
Tüm konuları özetlemek adına numpy'ın en çok kullanılan özelliklerini içeren bir cheatsheet

Not : Daha okunaklı olması açısından görüntüyü yeni sekmede açmanızı tavsiye ederim. 

![](https://cdn-images-1.medium.com/max/2560/1*7nAmFA6nKv_XvyKLRCFK4g.png)

---
---
# Bana Ulaşın!!

[<img height="32" width="32" src="https://simpleicons.org/icons/linkedin.svg"/>](https://www.linkedin.com/in/secilaykutal/)
[<img height="32" width="32" src="https://simpleicons.org/icons/github.svg"/>](https://github.com/seccily/)
[<img height="32" width="32" src="https://simpleicons.org/icons/gmail.svg"/>](mailto:secilaykutal99@gmail.com)
